=== dorohovichandrey/RMITask/server/data/footballer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/footballers"
        xmlns:tns="http://www.example.com/footballers"
        elementFormDefault="qualified">
    <element name="footballer" type="tns:Footballer"></element>


    <element name="footballers">
        <complexType>
            <sequence>
                <element ref="tns:footballer" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Footballer">
        <sequence>
            <element name="id" type="tns:Id" />
            <element name="name" type="string" />
            <element name="surname" type="string" />
            <element name="age" type="int" />
            <element name="teamId" type="int"/>
        </sequence>
    </complexType>

    <simpleType name="Id">
        <restriction base="positiveInteger">
            <maxInclusive value="10000"></maxInclusive>
        </restriction>
    </simpleType>
</schema>

=== dorohovichandrey/RMITask/server/data/footballers.xml
<footballers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/footballers"
          xsi:schemaLocation="http://www.example.com/footballers footballer.xsd">
   <footballer>
       <id>1</id>
       <name>Dario</name>
       <surname>Srna</surname>
       <age>35</age>
       <teamId>1</teamId>
   </footballer>
    <footballer>
        <id>2</id>
        <name>Sergei</name>
        <surname>Kornilenko</surname>
        <age>34</age>
        <teamId>2</teamId>
    </footballer>
</footballers>
