=== dorohovichandrey/RMITask/server/data/team.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/teams"
        xmlns:tns="http://www.example.com/teams"
        elementFormDefault="qualified">
    <element name="team" type="tns:Team"></element>


    <element name="teams">
        <complexType>
            <sequence>
                <element ref="tns:team" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Team">
        <sequence>
            <element name="id" type="tns:Id" />
            <element name="name" type="string" />
            <element name="city" type="string" />
        </sequence>
    </complexType>

    <simpleType name="Id">
        <restriction base="positiveInteger">
            <maxInclusive value="10000"></maxInclusive>
        </restriction>
    </simpleType>
</schema>

=== dorohovichandrey/RMITask/server/data/teams.xml
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.example.com/teams"
             xsi:schemaLocation="http://www.example.com/teams team.xsd">
    <team>
        <id>1</id>
        <name>BATE</name>
        <city>Borisov</city>
    </team>
    <team>
        <id>2</id>
        <name>Granit</name>
        <city>Mikashevichi</city>
    </team>
</teams>
